github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/sprout-video-downloader",
"https://store.serp.co/product-details/product/sprout-video-downloader",
"https://serp.co/products/sprout-video-downloader/reviews/",
]
