github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/sprout-video-downloader",
"https://serp.co/products/sprout-video-downloader/reviews/",
"https://whop.com/serp-downloaders/sprout-video-downloader/",
"https://addons.mozilla.org/en-US/firefox/addon/sprout-video-downloader/",
"https://chromewebstore.google.com/detail/sprout-video-downloader/cdadhadfngaaemiiembbmldhamnpkmkf"
]
